### ISSUE TITLE
Not resetting the WiFi module before starting the driver causes stall

### ISSUE THREAD

**Issue by unizippro** [BlackbirdHQ/ublox-short-range-rs#17]
The driver will stall if the WiFi module is not reset before starting the driver.
Since the driver utilizes `defmt` as the logging framework it is not possible to get logs out without resetting the processor. Which in my application also resets the WiFi module. Meaning there is no logs for the issue.

**Comment by MathiasKoch** [comment]
I believe this was fixed by https://github.com/BlackbirdHQ/ublox-short-range-rs/commit/13034c528ff8e07ca14253bdd606373c76d342d3
