### ISSUE TITLE
arduino_nano33iot

### ISSUE THREAD

**Issue by Geens** [BlackbirdHQ/ublox-short-range-rs#47]
This looks like a great crate. I would love to use it with the Arduino Nano 33 IoT. The arduino_nano33iot crate (version 0.7.0) uses embedded-hal ^0.2. Is there a way to make this crate compatible? E.g. with https://github.com/ryankurte/embedded-hal-compat

I can't seem to figure out how to do this. Help would be much appreciated. This is my list of dependencies:

arduino_nano33iot = { version = "0.7.0", features = ["usb"] }
atsamd-hal = { version = "0.14", features = ["usb", "unproven"] }
cortex-m = "0.7"
cortex-m-rtic = "1"
embedded-hal = "0.2"
panic-semihosting = "0.6"
systick-monotonic = "1"
usb-device = "0.2"
usbd-serial = "0.1"

**Comment by Geens** [comment]
I believe I figured out the problem. the bbqueue crate requires the thumbv6 feature to compile with arduino_nano33iot. I will try an make a full example and open a pull request

**Comment by MathiasKoch** [comment]
Huh. I was not aware of https://github.com/ryankurte/embedded-hal-compat but i cannot see why that wouldn't work here :) 

I think you should be able to just include `bbqueue` as a dependency in your own repo with the `thumbv6` feature enabled as:
`bbqueue = { version = "*", features = ["thumbv6"] }`
